Connecting to server on port 3002...
Connected to server on port 3002
Something went wrong running your bot: 'Strategy' object has no attribute 'done_heuristic'
Traceback (most recent call last):
File "/Users/sanjilee/development/lebrawnjame_mm30/main.py", line 245, in serve
response = strategy.steer_input(planes)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/sanjilee/development/lebrawnjame_mm30/strategy/sanji_strategy.py", line 79, in steer_input
if self.done_heuristic:
^^^^^^^^^^^^^^^^^^^
AttributeError: 'Strategy' object has no attribute 'done_heuristic'
Something went wrong running your bot: 'Strategy' object has no attribute 'done_heuristic'
Traceback (most recent call last):
File "/Users/sanjilee/development/lebrawnjame_mm30/main.py", line 245, in serve
response = strategy.steer_input(planes)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/sanjilee/development/lebrawnjame_mm30/strategy/sanji_strategy.py", line 79, in steer_input
if self.done_heuristic:
^^^^^^^^^^^^^^^^^^^
AttributeError: 'Strategy' object has no attribute 'done_heuristic'
Something went wrong running your bot: 'Strategy' object has no attribute 'done_heuristic'
Traceback (most recent call last):
File "/Users/sanjilee/development/lebrawnjame_mm30/main.py", line 245, in serve
response = strategy.steer_input(planes)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/sanjilee/development/lebrawnjame_mm30/strategy/sanji_strategy.py", line 79, in steer_input
if self.done_heuristic:
^^^^^^^^^^^^^^^^^^^
AttributeError: 'Strategy' object has no attribute 'done_heuristic'
Your bot failed to respond 3 times in a row (is your bot broken?) and was disconnected