Connecting to server on port 3001...
Connected to server on port 3001
Something went wrong running your bot: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
File "/Users/sanjilee/development/lebrawnjame_mm30/main.py", line 245, in serve
response = strategy.steer_input(planes)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/sanjilee/development/lebrawnjame_mm30/strategy/sanji_strategy.py", line 81, in steer_input
for friendly, enemy in closest_plane:
^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
Something went wrong running your bot: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
File "/Users/sanjilee/development/lebrawnjame_mm30/main.py", line 245, in serve
response = strategy.steer_input(planes)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/sanjilee/development/lebrawnjame_mm30/strategy/sanji_strategy.py", line 81, in steer_input
for friendly, enemy in closest_plane:
^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
Something went wrong running your bot: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
File "/Users/sanjilee/development/lebrawnjame_mm30/main.py", line 245, in serve
response = strategy.steer_input(planes)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/sanjilee/development/lebrawnjame_mm30/strategy/sanji_strategy.py", line 81, in steer_input
for friendly, enemy in closest_plane:
^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
Your bot failed to respond 3 times in a row (is your bot broken?) and was disconnected